spring:
  application:
    name: zuul-server
server:
  port: 8077
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
  instance:
    instance-id: eureka-zuul-8077
    prefer-ip-address: true
zuul:
  routes:
    zuul-client-user: #路由别名
      path: /userZuul/**
      service-id: eureka-client-user
  #什么都不设置代表不过滤任何信息 "Cookie", "Set-Cookie", "Authorization"
  sensitive-headers: Cookie,Set-Cookie,Authorization
  ignored-services: '*' # *忽略所有服务；/**/user/* #忽略所有包含/user/的地址请求
#  prefix: zuul_user #路由前缀，即URL后缀
#  strip-prefix: true