spring:
  # 服务名称
  application:
    name: eureka-client-user
  # 数据源
  datasource:
    name: user
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  #jsp前后缀
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    # 出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
    throw-exception-if-no-handler-found: true
  # 不要为工程中的资源文件建立映射
  resources:
    add-mappings: false
server:
  port: 8781
  context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
  instance:
    prefer-ip-address: true # 优先注册IP地址而不是hostname
    instance-id: eureka-client-user_1

# 配置日志
logging:
  config: classpath:logback-spring.xml

info:
  app.name: client-8781
  company.name: www.hyz.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hyz.user.domain.entity