spring:
  application:
    name: eureka-service-ha
server:
  port: 8762
eureka:
  instance:
    # when profile=peer2, hostname=peer2
    hostname: peer2
  client:
    service-url:
      # register self to peer1 peer3
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
    register-with-eureka: false #false 表示不向注册中心中注册自己
    fetch-registry: false #false 表示自己端就是注册中心,我的职责就是维护服务实例，并不需要去检索服务